### ISSUE TITLE
roc_auc doesn't work 

### ISSUE THREAD

**Issue by jaeyk** [snfagora/autotextclassifier#5]
`roc_auc` metric doesn't work. The problem may stem from the fact that the `stats::predict()` function produces binary predicted outputs.

**Comment by milandv** [comment]
I've used caret::predict() for this which supports class probabilities. 

e.g. `predict(model = mod, newdata = some_new_data, type="prob")`

**Comment by jaeyk** [comment]
@milandv fixed it. the `predict()` function comes from the `stats` package. To pull the probabilities for each class, one needs to use `roc_auc()` rather than using the `metrics()` (generic function for evaluation). Thanks for the tip.
